// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vazbmthmfgtaypjpkeyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhemJtdGhtZmd0YXlwanBrZXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NTk5NTIsImV4cCI6MjA5MDQzNTk1Mn0.ocl9I-ynsdiUs94X9p6tVzoyyMDsJnrTKxNAB0TeDCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);